# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_y_fn": "00_core.ipynb",
         "UbiDeployment": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://free-soellingeraj.github.io/prod-mod-face-profile/"

git_url = "https://github.com/free-soellingeraj/prod-mod-face-profile/tree/master/"

def custom_doc_links(name): return None
