# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/13_interfaces_types.ipynb (unless otherwise specified).

__all__ = ['check_collection']

# Cell


# Cell
def check_collection(val):
    if type(val) == dict:
        raise Exception('`dict` not a supported output type.')

    types = list({type(v) for v in val})
    if len(types) > 1:
        raise Exception('Mixed type collections not supported.')

    if types[0] == int:
        return 'array_int'
    elif types[0] == float:
        return 'array_float'
    elif types[0] == str:
        return 'array_str'
