# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Deployment": "00_core.ipynb",
         "check_collection": "13_interfaces_types.ipynb",
         "make_ubiops_spec": "14_serving_ubiops.ipynb",
         "UbiOpsInputRequestData": "14_serving_ubiops.ipynb",
         "UbiOpsOutputRequestData": "14_serving_ubiops.ipynb",
         "UbiOpsClient": "14_serving_ubiops.ipynb",
         "ubiops_type_mapping": "14_serving_ubiops.ipynb",
         "UnexpectedInputProvided": "15_exceptions.ipynb",
         "ExpectedInputMissing": "15_exceptions.ipynb",
         "DataTypeNotImplemented": "15_exceptions.ipynb",
         "RequestData": "16_serving_client.ipynb",
         "Client": "16_serving_client.ipynb"}

modules = ["core.py",
           "client.py",
           "interfaces/types.py",
           "serving/ubiops.py",
           "exceptions.py",
           "serving/client.py"]

doc_url = "https://free-soellingeraj.github.io/mod/"

git_url = "https://github.com/free-soellingeraj/mod/tree/master/"

def custom_doc_links(name): return None
