# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Deployment": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://free-soellingeraj.github.io/mod/"

git_url = "https://github.com/free-soellingeraj/mod/tree/master/"

def custom_doc_links(name): return None
