# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/15_exceptions.ipynb (unless otherwise specified).

__all__ = ['UnexpectedInputProvided', 'ExpectedInputMissing', 'DataTypeNotImplemented']

# Cell

## imports

# Cell
class UnexpectedInputProvided(Exception):
    """Interrupts execution if unexpected input is provided."""
    pass

class ExpectedInputMissing(Exception):
    """Interrupts execution if expected input is missing."""
    pass

class DataTypeNotImplemented(Exception):
    """Interrupts execution if requested data type is not implemented"""
    pass